#!/bin/bash
# TODO: check why "set -e" does not work.
set -o errexit -o nounset -o pipefail

PROGRAM_NAME="Slime Mold"
PROGRAM_SHORT_NAME="sm"

SCRIPT_DIR=$(dirname $0)
INCLUDE_DIR="${SCRIPT_DIR}/sh_inc"
. ${INCLUDE_DIR}/lockfile.sh
. ${INCLUDE_DIR}/parse_cmd.sh
. ${INCLUDE_DIR}/appliance.sh
. ${INCLUDE_DIR}/switch.sh
. ${INCLUDE_DIR}/vm.sh
. ${INCLUDE_DIR}/ssh.sh

ERR=0
if [ "${?}" != "0" ]; then
    ERR=1
    echo "exit status: ${?}"
fi

parse_cmd $*

exit ${ERR}
